name: CI/CD Pipeline

on:
  push:
    branches:
      - master


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image to Docker Hub
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t rojasfraga2024/wedding:${{ github.sha }} -t rojasfraga2024/wedding:latest .
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
          docker push rojasfraga2024/wedding:${{ github.sha }}
          docker push rojasfraga2024/wedding:latest